### ISSUE TITLE
Alternative Sorting Mechanisms

### ISSUE THREAD

**Issue by mjcarroll** [nikku/wuffle#72]
Ideally, it would be nice to have alternative ways of sorting the columns in addition to the "semantic sort".  When dealing with a larger backlog of issues, it's helpful to see the newest issues/prs float to the top of the column to get an at-a-glance look at the incoming issues.

I would propose adding at a minimum a sort by issue creation date.

**Comment by nikku** [comment]
As mentioned [here](https://github.com/nikku/wuffle/issues/54) this is something we'll not support any time soon. What would be the benefit?

**Comment by mjcarroll** [comment]
I didn't see that previous issue, but I understand your logic.

As to the beneift, we used waffle previous to manage issues across several larger orgs (github.com/ros2), so manually sorting would be cumbersome in that application.  It was particularly helpful in triaging incoming tickets.

I'll probably attempt to do this in my own fork, and if it's something that would be a reasonably clean enhancement, PR it back.  Otherwise I'll just modify for our use.

Thanks again for open sourcing this! It's a fantastic tool.

**Comment by nikku** [comment]
> It was particularly helpful in triaging incoming tickets.

Just to understand your scope a bit better: How many new issues are there to triage per week / month so that missing sorting is an issue? I'd always go for filtering instead and filters such as created:lastWeek created:lastMonth created_before:... are on my roadmap.

> Thanks again for open sourcing this! It's a fantastic tool.

You're welcome. I've built it in the hope that it was useful for you and I'm happy to hear that you use the board in a non-trivial environment. That's what it was built for :smile:.
