### ISSUE TITLE
Do not override GitHub labels but rather add and remove

### ISSUE THREAD

**Issue by nikku** [nikku/wuffle#77]
__Describe the Bug__

The board forcefully overrides column labels when issues are being moved via automatic dev flow. This can lead to the situation that labels added by external parties are being overridden.

__Steps to Reproduce__

* External party opens PR
* Board moves PR to `needs review`
* External party adds `foo` label
* Board resets labels, dropping `foo`, adding `needs review`

__Expected Behavior__

* Board only adds and removes labels it controls itself. No additional labels are being touched.

__Environment__

- Browser: Any
- OS: Any
- Board Version: v0.29.0

**Comment by nikku** [comment]
@piyushk I've seen you fixed this via https://github.com/SonyAI/wuffle_contrib/commit/1f2dac09742fcb2988efdbd82bec74508f7f0a67. 

Did it work without unintended side-effects? Do you mind if I adopt your solution?

**Comment by piyushk** [comment]
I'm afraid there are side-effects, which is why I never PRed the solution. Since there is a short delay between add/remove, the card tends to jump around on the board. For instance, If I move the card from In Review to In Progress (i.e left) manually, I add the `In Progress` label and then remove the `In Review` label. The card jumps to `In Progress`, back to `In Review`, and then to `In Progress`. As long as you're moving cards right (typical flow), I think the behavior works fine.

Please feel free to adopt the solution however you'd like if you can resolve the side-effect above. I had to implement it because wuffle was removing a label added by a different bot.

**Comment by nikku** [comment]
Thanks for the heads up. Will need to wrap my head around that issue then, some day :wink:

**Comment by nikku** [comment]
Closed via https://github.com/nikku/wuffle/commit/2ab671c0fd06fd6ef323b527d0e94627ce38351d.

**Comment by nikku** [comment]
I believe I've come up with something stable enough via https://github.com/nikku/wuffle/commit/7f9e59fc8b14a8d4de34e226ea67c1322f7b603a and https://github.com/nikku/wuffle/commit/2ab671c0fd06fd6ef323b527d0e94627ce38351d.

The board should really not interfere with anything outside of it, forcefully override labels and so forth.
